name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version-file: .tool-versions
        cache: npm

    - name: Clean install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint && git diff --exit-code

  test:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16.x, 18.x, 20.x, 22.x]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Clean install dependencies
      run: npm ci

    - run: npm run test --reporter=verbose
      env:
        CI_OS: ${{ runner.os }}

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version-file: .tool-versions
        cache: npm

    - name: Clean install dependencies
      run: npm ci

    - run: npm run test-coverage -- --reporter=verbose
      env:
        CI_OS: ${{ runner.os }}

    - uses: actions/upload-artifact@v4
      with:
        name: test-coverage
        path: coverage/

    - uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        directory: ./coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build-and-run:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16.x, 18.x, 20.x, 22.x]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Clean install dependencies
      run: npm ci

    - run: npm run build

    - run: node bin/repopack

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: repopack-output-${{ matrix.os }}-${{ matrix.node-version }}.txt
        path: repopack-output.txt

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
      - run: npm ci
      - name: Run npm audit
        run: npm audit

  typos:
    name: "Check for typos"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Check for typos"
        uses: "crate-ci/typos@v1.25.0"
